services:
  - name: storezen-api
    type: web
    region: oregon
    buildCommand: pnpm install && pnpm turbo run build --filter=@storepk/api
    startCommand: node apps/api/dist/index.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"

databases:
  - name: storezen-db
    plan: free
    region: oregon