/** Matches API `TEMPLATE_CSV_HEADERS` — keep labels non-technical. */
export const IMPORT_FIELD_ORDER = [
  "name",
  "slug",
  "description",
  "price",
  "compare_at_price",
  "stock",
  "category",
  "vendor",
  "product_type",
  "sku",
  "image",
  "images",
  "tags",
  "status",
  "meta_title",
  "meta_desc",
  "urdu_description",
  "tiktok_caption",
  "whatsapp_text",
  "weight",
  "requires_shipping",
] as const;

export type ImportFieldKey = (typeof IMPORT_FIELD_ORDER)[number];

export const IMPORT_FIELD_LABEL: Record<ImportFieldKey, string> = {
  name: "Title",
  slug: "Handle",
  description: "Description",
  price: "Price",
  compare_at_price: "Compare at price",
  stock: "Stock quantity",
  category: "Category",
  vendor: "Vendor / Brand",
  product_type: "Product type",
  sku: "SKU / Barcode",
  image: "Main image",
  images: "Additional images (comma separated)",
  tags: "Tags (comma separated)",
  status: "Status (active/draft)",
  meta_title: "SEO title",
  meta_desc: "SEO description",
  urdu_description: "Urdu description",
  tiktok_caption: "TikTok caption",
  whatsapp_text: "WhatsApp message",
  weight: "Weight (grams)",
  requires_shipping: "Requires shipping (TRUE/FALSE)",
};

export const TEMPLATE_CSV_HEADERS = [
  "Title",
  "Handle",
  "Description",
  "Price",
  "Compare at price",
  "Stock quantity",
  "Category",
  "Vendor / Brand",
  "Product type",
  "SKU / Barcode",
  "Main image",
  "Additional images (comma separated)",
  "Tags (comma separated)",
  "Status (active/draft)",
  "SEO title",
  "SEO description",
  "Urdu description",
  "TikTok caption",
  "WhatsApp message",
  "Weight (grams)",
  "Requires shipping (TRUE/FALSE)",
];